---

- name: Playbook for showing variable usage
  hosts: localhost
  gather_facts: yes
  vars:
    list_variable: []
    var_test1: false
    var_test2:
      - item1
      - item2
      - item3
    var_test3:
      user:
        name: "Lab Person"
        purpose: "Test the Lab"
    var_dict:
       { item_key1: value1, item_key2: value2, item_key3: value3 }

  vars_files: file-vars.yml

  tasks:

  - name: Output some varaibles
    debug: 
      msg: "{{ list_variable }}"

  - name: Some conditionals
    debug:
      msg: This checks for some variable
    when: var_test1 | bool

  - name: Looping through list variable
    debug:
      msg: "{{ item }}"
    with_items: "{{ var_test2 }}"

  - name: Nested varibles
    debug:
      msg: "{{ var_test3.user.name }}"

  - name: Dictionary variables
    debug:
      msg: "Item key is {{ item.key }} and the value is {{ item.value }}"
    with_dict: "{{ var_dict }}"

  - name: Facts display
    debug:
      msg: "Ansible facts date time formatted iso8601 - {{ ansible_facts['date_time']['iso8601'] }} - and IP Address {{ ansible_facts['all_ipv4_addresses'] }}"


  - name: Jinja Stuffs
    debug:
      msg: "{{ var_test3.user.purpose | upper }}"

  - name: More Jinja Stuff
    debug:
      msg: "{{ 13.4 *  53 }}"

  - name: More Jinja Stuff
    debug:
      msg: "{% for item in var_test2 %} {{ item }} {% endfor %}"

  - name: Find all files with the word password in the current directory 
    shell: "{{ command }}"
    vars: 
      - command: "grep -R 'password' ."
    register: where_is_password
   
  - name: debug where_is_password
    debug:
      msg: "{{ where_is_password.stdout }}"
