---

- name: Playbook for showing variable usage
  hosts: localhost
  gather_facts: yes
  vars:
    array_variable: []
    var_test1: false
    var_test2:
      - item1
      - item2
      - item3
    var_test3:
      user:
        name: "Lab Person"
        purpose: "Test the Lab"

  vars_files: file-vars.yml

  tasks:

  - name: Output some varaibles
    debug: 
      msg: "{{ array_variable }}"

  - name: Some conditionals
    debug:
      msg: This checks for some variable
    when: var_test1 | bool

  - name: Looping through list variable
    debug:
      msg: "{{ item }}"
    loop: "{{ var_test2 }}"

  - name: Nested varibles
    debug:
      msg: "{{ var_test3.user.name }}"

  - name: Facts display
    debug:
      msg: "Ansible facts date time formatted iso8601 - {{ ansible_facts['date_time']['iso8601'] }} - and IP Address {{ ansible_facts['all_ipv4_addresses'] }}"


  - name: Jinja Stuffs
    debug:
      msg: "{{ var_test3.user.purpose | upper }}"

  - name: More Jinja Stuff
    debug:
      msg: "{{ 13.4 *  53 }}"

  - name: More Jinja Stuff
    debug:
      msg: "{% for item in var_test2 %} {{ item }} {% endfor %}"

